### ISSUE TITLE
Some words can not be translated

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#15]
Some parts of the interface can not be translated:

Send
Type a username
Type a message
All messages
You:

**Comment by Pls** [comment]
I think you should be able to translate those strings using templates/pmm-thread.html.twig file. Doing this myself right now, will report back if it works as expected.

**Comment by ZenImagine** [comment]
It is a solution, but if the module is updated it will also update the templates. It will be easier to do this on `/admin/config/regional /translate`

**Comment by Pls** [comment]
Sure, it's not ideal solution as you said, you would have to update overriden template file and merge those changes. But it's a solution that works :)

So, it's confirmed and works as expected. After copying that file to my theme directory, I managed to override those strings.

**Comment by ZenImagine** [comment]
Thank you. I'm going to do that, hoping it's temporary ;-)

**Comment by ZenImagine** [comment]
I failed to translate :

Type a username
All messages
You:

**Comment by Pls** [comment]
Ok, so "Type a username" is unfortunetely hardcoded in pmm-views.js (182 line). So, temp solution would be to modify that file. If you use composer for adding this module, then you could patch it with your own patch using composer-patches. Not sure if you're familiar with that. Other solution would be just exclude this module from composer and use it as your own fork with modifications. And again then you should track any changes made by the owner. Hope this helps you. 

"All Messages" and "You" strings are translatable as they are put through t() function. Please search these string exactly as it's said in my quotes. As lowercase and uppercase strings does make a difference and that's why you maby can't find those strings. And there is no ":" in "You" string.

I am testing this awesome module too, finding some bugs, will report back also. Let's make it awesome :)

**Comment by ZenImagine** [comment]
Thank you. Do you have this problem ?

https://github.com/jez500/Private-Message-Messenger/issues/2

Answer the question so that I erase this comment.

**Comment by jez500** [comment]
Hey @Pls @ZenImagine 

I'm a bit snowed under with other work at the moment but will be coming back to these issues as I will be implementing this on a production site. In the meantime I am more than happy to look at & merge pull requests for any fixes you can implement.

**Comment by ZenImagine** [comment]
@jez500 Very well thank you. Can you answer this question https://github.com/jez500/Private-Message-Messenger/issues/11, as I test this feature ?

**Comment by jez500** [comment]
All strings are translatable now, no strings should be hard coded in templates, etc
